<?php

namespace LoginBundle\Repository;

/**
 * GithubTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GithubTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
