main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    resource: "@LoginBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
  path: /logout