# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        LoginBundle\Entity\User: sha512
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main_provider:
            entity:
                class: LoginBundle:User
                property: username
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main_provider
            form_login:
                login_path: /login
                check_path: /login
                use_referer: true 
            # http://symfony.com/doc/current/security/remember_me.html
            remember_me:
                secret:   '%secret%'
                lifetime: 432000 # 5 days in seconds
                path:     /
            logout:
                path:   /logout
                target: /